name: Tests
on:
  pull_request: null
  push:
    branches:
      - main
      - devel
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: "python -m pip install --upgrade pip

          pip install pytest pytest-cov toml flake8 black mypy

          pip install -e .

          "
      - name: Run tests
        run: sh tests/run_tests_with_coverage.sh
      - name: Run mypy
        run: mypy findskel || true
      - name: Run flake8
        run: flake8 --ignore=E501 || true
